version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run:
          name: "Qual versão do docker?"
          command: docker -v
      - run:
          name: "Posso fazer pull de imagens?"
          command: docker build -t minha-versao-do-postman .
      - run:
          name: "A imagem está listada?"
          command: docker images
      - run:
          name: "Usando a imagem para rodar o container"
          command: docker run "GoogleTest.postman_collection.json -r htmlextra"

