version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run:
          name: "Qual versão do docker?"
          command: docker -v
      - run:
          name: "Posso fazer pull de imagens?"
          command: docker pull postman/newman


