version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Run"
          command: |
            npm -v
            npm install
            npm run report